---

- name: changing hostname
  hostname:
    name: "{{ inventory_hostname_short }}"
  register: "hostname_status"
  become: true
  when: ansible_hostname != inventory_hostname_short

- name: restarting node
  shell: sleep 2 && shutdown -r now "rebooting to complete hostname change"
  async: 1
  poll: 0
  ignore_errors: true
  become: true
  when: >
        (change_hostname_reboot is defined and
        change_hostname_reboot ) and
        hostname_status.changed

- name: waiting for node reboot
  wait_for:
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: 22
    search_regex: OpenSSH
    delay: 10
  vars:
    ansible_connection: local
  become: false
  when: >
        (change_hostname_reboot is defined and
        change_hostname_reboot ) and
        hostname_status.changed

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ inventory_hostname_short }}'
    state: present
