- name: Kubernetes Master
  hosts: master
  any_errors_fatal: true
  remote_user: odroid
  become: true
  roles:
  - role: kubernetes
    mode: master

- name: Kubernetes Nodes
  hosts: nodes
  any_errors_fatal: true
  remote_user: odroid
  become: true
  roles:
  - role: kubernetes
    mode: node
