- name: Update apt package index
  apt: update_cache=yes cache_valid_time={{ aptcachetime }} autoremove=no upgrade=no

- name: Packages to install
  apt:
    name: "{{ item }}"
    force: yes
    state: present
  with_items:
    - hdparm
    - iperf
    - mtr-tiny
    - socat
    - jq
    - glusterfs-server
