- name: Create the flannel resources
  template: src=cni/flannel.yml dest=/etc/kubernetes/kube-flannel.yml

- name: Create the flannel resources
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  command: kubectl create -f /etc/kubernetes/kube-flannel.yml
